In [1]:
# Imports 
import pandas as pd

In [2]:
# Load Data
df = pd.read_csv("../Datasets/spam.csv", encoding="ISO-8859-1")
df

,type,text,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN
...,...,...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,NaN,NaN,NaN
5568,ham,Will ï¿½_ b going to esplanade fr home?,NaN,NaN,NaN
5569,ham,"Pity, * was in mood for that. So...any other s...",NaN,NaN,NaN
5570,ham,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN
5571,ham,Rofl. Its true to its name,NaN,NaN,NaN

In [3]:
# Manage Data
y = (df["type"] == "spam").astype(int)

# Frequently reused data
textList, x =  df["text"], pd.DataFrame()

### Feature Engineering

In [4]:
# Simple Feature Engineering

# Returns number of characters per text
def numChar(column):
    return [len(line) for line in column] 
x["length"] = numChar(textList)

# TODO: add more feature engr

In [5]:
# Returns the DataFrame of the Engineered Features
def featureEngineering(filepath):
    # First Load Data
    df = pd.read_csv(filepath, encoding="ISO-8859-1")
    
    # Now set up x, y for data and results
    features = pd.DataFrame()
    labels = (df["type"] == "spam").astype(int)

    # Store texts to be reused
    textList = df["text"] 

    # Set up the Feature Engineered Columns
    features["length"] = numChar(textList)
    
    # Training & Testing Split
    return features, labels

In [6]:
featureEngineering("../Datasets/spam.csv")

(      length
 0        111
 1         29
 2        155
 3         49
 4         61
 ...      ...
 5567     162
 5568      39
 5569      57
 5570     125
 5571      26

 [5572 rows x 1 columns],
 0       0
 1       0
 2       1
 3       0
 4       0
        ..
 5567    1
 5568    0
 5569    0
 5570    0
 5571    0
 Name: type, Length: 5572, dtype: int64)