In [68]:
# Imports 
import pandas as pd
from sklearn.model_selection import train_test_split

In [32]:
# Load Data
df = pd.read_csv("../Datasets/spam.csv", encoding="ISO-8859-1")
df

,type,text,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN
...,...,...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,NaN,NaN,NaN
5568,ham,Will ï¿½_ b going to esplanade fr home?,NaN,NaN,NaN
5569,ham,"Pity, * was in mood for that. So...any other s...",NaN,NaN,NaN
5570,ham,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN
5571,ham,Rofl. Its true to its name,NaN,NaN,NaN

In [36]:
# Manage Data
y = (df["type"] == "spam").astype(int)

# Frequently reused data
textList, x =  df["text"], pd.DataFrame()

### Feature Engineering

In [46]:
# Simple Feature Engineering

# Returns number of characters per text
def numChar(column):
    return [len(line) for line in column] 
x["length"] = numChar(textList)

# TODO: add more feature engr

In [98]:
# Returns the DataFrame of the Engineered Features
def featureEngineering(filepath):
    # First Load Data
    df = pd.read_csv(filepath, encoding="ISO-8859-1")
    
    # Now set up x, y for data and results
    features = pd.DataFrame()
    labels = (df["type"] == "spam").astype(int)

    # Store texts to be reused
    textList = df["text"] 

    # Set up the Feature Engineered Columns
    features["length"] = numChar(textList)
    
    # Training & Testing Split
    return train_test_split(features, labels, test_size=0.30, random_state=42)

In [99]:
featureEngineering("../Datasets/spam.csv")

[      length
 708      155
 4338      34
 5029      84
 4921     156
 2592     117
 ...      ...
 3772      71
 5191      22
 5226      45
 5390      26
 860       35

 [3900 rows x 1 columns],
       length
 3245     151
 944      221
 1044     101
 2484     124
 812      152
 ...      ...
 2505      36
 2525     163
 4975      54
 650       66
 4463      44

 [1672 rows x 1 columns],
 708     1
 4338    0
 5029    0
 4921    0
 2592    0
        ..
 3772    0
 5191    0
 5226    0
 5390    0
 860     0
 Name: type, Length: 3900, dtype: int64,
 3245    0
 944     0
 1044    1
 2484    0
 812     1
        ..
 2505    0
 2525    0
 4975    0
 650     0
 4463    0
 Name: type, Length: 1672, dtype: int64]